import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import Notificated from "../components/Notificated";

import Footer from "../components/Footer";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/lib/provider/AuthProvider";
import QueryProvider from "@/lib/provider/QueryProvider";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Order Coffee Online | Fresh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-orange-50 ${nunito.className}`}>
        <AuthProvider>
          <QueryProvider>
            <Notificated />
            <Navbar />
            <main>{children}</main>
            <Footer />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
